#!/bin/sh
# ================================================================= #
# ░█▀▄░█▀▀░█▀█░█░█░█▄█░█▀▄░█▀▀                                      #
# ░█▀▄░▀▀█░█▀▀░█▄█░█░█░█▀▄░█░░                                      #
# ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀░▀░▀░▀▀▀                                      #
#                                                                   #
# Usergh0st - https://github.com/Usergh0st/dotfiles                 #
# Description - bspwmrc configuration rules and behavior            #
# Date = 01.09.2026 07:43 P.M.                                      #
# Copyright (C) 2025-2026 Usergh0st <tsohg.uncork054@passinbox.com> #
# ================================================================= #

# ░█▀▀░█▀█░█░█
# ░█▀▀░█░█░▀▄▀
# ░▀▀▀░▀░▀░░▀░

# -- Environment variables --
export _JAVA_AWT_WM_NONREPARENTING=1
export PATH="${HOME}/.config/bspwm/src:${PATH}"
export XDG_CURRENT_DESKTOP='bspwm'

# ░█░█░█▀█░█▀▄░█░█░█▀▀░█▀█░█▀█░█▀▀░█▀▀░█▀▀
# ░█▄█░█░█░█▀▄░█▀▄░▀▀█░█▀▀░█▀█░█░░░█▀▀░▀▀█
# ░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀

# -- Monitors --
# -- If you don't like the current resolution you have. --
# -- Replace the script [MonitorSetup.sh] with [CustomResolution.sh] and edit that's file. --
# -- If you want a custom resolution go to this file -> [~/.config/bspwm/src] edit that's file. --
# -- CustomResolution.sh --
MonitorSetup.sh

# ░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀
# ░█░░░█░█░█░█░█▀▀░░█░░█░█
# ░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀

# -- External Rules --
bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules.sh

# -- Aesthetics --
bspc config border_width 1
bspc config window_gap 3
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config focused_border_color "#6f2524"
bspc config normal_border_color "#191f1a"
bspc config presel_feedback_color "#1d1918"

# -- General behavior --
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# -- States --
bspc config automatic_scheme longest_side
bspc config split_ratio 0.50

# -- Layout --
bspc config initial_polarity second_child
bspc config removal_adjustment true

# ░█▀▀░▀█▀░█▀█░█▀▄░▀█▀░▀█▀░█▀█░█▀▀
# ░▀▀█░░█░░█▀█░█▀▄░░█░░░█░░█░█░█░█
# ░▀▀▀░░▀░░▀░▀░▀░▀░░▀░░▀▀▀░▀░▀░▀▀▀

# -- Vmware Clip & Others --
wmname LG3D &>/dev/null &
vmware-user-suid-wrapper &>/dev/null &

# -- Launch polybars --
# -- barpwm --
# -- homebar --
# ~/.config/bspwm/polybar/homebar/launch.sh &
~/.config/bspwm/polybar/barpwn/launch.sh &

# -- Start sxhkd daemon hotkey --
pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/sxhkdrc & }

# -- Start picom compositor --
# -- You have 2 configs of picom, with virtual machines and physical hardware --
# -- Default config used is "picom-machines-virtuals" for virtual machines --
# -- You have animations with configuration "picom-physical-hardware" --
# pidof -q picom || { picom --config "${HOME}"/.config/bspwm/picom/picom-physical-hardware.conf & }
pidof -q picom || { picom --config "${HOME}"/.config/bspwm/picom/picom-machines-virtuals.conf & }

# -- Restore wallpaper with nitrogen --
# -- Remplaze with script in the future --
# -- I made the script but it's very simple --
WallSelect.sh
