;       ░█▀▄░█▀█░█▀▄░█▀█░█░█░█▄█
;       ░█▀▄░█▀█░█▀▄░█▀▀░█▄█░█░█
;       ░▀▀░░▀░▀░▀░▀░▀░░░▀░▀░▀░▀
;
;       Usergh0st - https://github.com/Usergh0st/dotfiles
;       Mail - tsohg.uncork054@passinbox.com
;       Date - 06.09.2026 09:39 A.M.
;
;       BARPWN | polybar for my dotfiles minimalist and elegant focused on hacking and pentesting.
;       Configuration built from scratch feel free to modify everything to your liking dear user.
;       If you want to learn more about polybar and modules see the wiki: [https://github.com/polybar/polybar/wiki]

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = modules.ini
include-file = ~/.config/bspwm/system.ini

[color]

bg = #0f0f0f
fg = #cd9191
mb = #812625

red = #4A201F
pink = #4B1F20
purple = #4F2425
blue = #732526
blue-icon = #474447
cyan = #882726
teal = #cd9191
green = #8f6565
lime = #4A201F
yellow = #261314
amber = #4B1F20
orange = #4F2425
brown = #732526
grey = #474447
indigo = #882726
blue-gray = #cd9191

[bar/barpwn]

monitor = ${env:MONITOR:}
monitor-fallback = Virtual-1
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 100%
height = 28

offset-x = 0
offset-y = 0

background = ${color.bg}
foreground = ${color.fg}

radius = 0

line-size = 3
line-color = ${color.blue}

padding = 0

module-margin-letf = 0
module-margin-right = 0

font-0 = "Cascadia Code:size=9;3"
font-1 = "Font Awesome 6 Free Solid:size=10;3"
font-2 = "Material Design Icons Desktop:size=13;3"
font-3 = "Material Design Icons Desktop:size=17;4"
#font-3 = "Font Awesome 6 Free Solid;size=9;3"

modules-left = launcher sep bspwm var network sep vpn
modules-center = title
modules-right = target var pulseaudio sep filesystem sep memory sep cpu sep updates sep power sep date

separator =
dim-value = 0.0

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
