;  ______              ______
; |   __ \.---.-.----.|   __ \.--.--.--.-----.
; |   __ <|  _  |   _||    __/|  |  |  |     |
; |______/|___._|__|  |___|   |________|__|__|
;                    __         __
; .--------.-----.--|  |.--.--.|  |.-----.-----.
; |        |  _  |  _  ||  |  ||  ||  -__|__ --|
; |__|__|__|_____|_____||_____||__||_____|_____|
;
; Usergh0st - https://github.com/Usergh0st/Machinepwn.git
; Mail - tsohg.uncork054@passinbox.com
; 10.06.2026 07:53 PM
;
; BARPWN MODULES | Configuration of the polybar modules, of the barpwn bar, edit this according to your taste, dear user.
; If you want to learn more about polybar modules see the wiki: https://github.com/polybar/polybar/wiki

###############################################

[module/launcher]
type = custom/text

label = " 󰕪"
label-foreground = ${color.cyan}
label-font = 2

click-left = rofi -show drun -theme ~/.config/bspwm/rofi/style-3.rasi

##############################################

[module/bspwm]
type = internal/bspwm

pin-workspaces = true
enable-click = true
enable-scroll = true
reverse-scroll = true
occupied-scroll = false

ws-icon-0 = 1;󰼏
ws-icon-1 = 2;󰼐
ws-icon-2 = 3;󰼑
ws-icon-3 = 4;󰼒
ws-icon-4 = 5;󰼓
ws-icon-5 = 6;󰼔
ws-icon-6 = 7;󰼕
ws-icon-7 = 8;󰼖
ws-icon-8 = 9;󰼗
ws-icon-default = ♟

format = <label-state>
format-font = 3

label-focused = %icon%
label-focused-padding = 2
label-focused-foreground = ${color.mb}
label-focused-background = ${color.yellow}

label-occupied = %icon%
label-occupied-padding = 2
label-occupied-foreground = ${color.mb}

label-urgent = %icon%
label-urgent-padding = 0

label-empty = %icon%
label-empty-foreground = ${color.purple}
label-empty-padding = 2
label-emply-background = ${color.mb}

label-separator = ""
label-separator-padding = 0

#############################################

[module/sep]
type = custom/text
label = " "
label-foreground = ${color.bg}

[module/var]
type = custom/text
label = " 󰇙 "
label-font = 2
label-foreground = ${color.blue}

############################################

[module/network]
type = internal/network
interface = ${system.sys_network_interface}

interface-type = wireless
; interface-type = wired

interval = 3.0
accumulate-stats = true
unknown-as-up = true

speed-unit = ""

format-connected = <ramp-signal> <label-connected>
format-connected-prefix = " 󱚸 "
format-connected-font = 3
format-connected-foreground = ${color.red}

ramp-signal-0 = "󰜒"
ramp-signal-1 = "󰜓"
ramp-signal-2 = "󰜔"
ramp-signal-3 = "󰩯"

label-connected = %local_ip%

format-disconnected = <label-disconnected>
format-disconnected-prefix = " 󰖪 "
format-disconnected-font = 3
format-disconnected-foreground = ${color.blue}

label-disconnected = "󰇉"
label-disconnected-foreground = ${color.red}

##########################################

[module/date]
type = internal/date

interval = 1.0

time = "%I:%M %P 󰥕"
format-background = ${color.mb}
format-foreground = ${color.fg}

format = <label>
format-font = 3

label = " %time% "
label-font = 1

#########################################

[module/power]
type = custom/text
label = " 󰤆 "
label-font = 2
label-foreground = ${color.red}

click-left = ~/.config/bspwm/src/powermenu.sh &

[module/updates]
type = custom/ipc

hook-0 = cat /var/cache/machinepwn/updates.txt 2>/dev/null
initial = 1

format = <label>
format-prefix = "󰯎"
format-prefix-font = 2
format-prefix-foreground = ${color.red}

label = "%output%"

click-left = OpenApps.sh --checkupdates
click-right = OpenApps.sh --update

##########################################

[module/cpu]
type = internal/cpu

interval = 0.5

format = <label>
format-prefix = "󰘚"
format-prefix-font = 2
format-prefix-foreground = ${color.mb}

label = %percentage%%

#########################################

[module/memory]
type = internal/memory

interval = 3

format = <label>
format-prefix = "󱇌"
format-prefix-font = 2
format-prefix-foreground = ${color.mb}

label = %used%

#########################################

[module/filesystem]
type = internal/fs

mount-0 = /

interval = 60

fixed-values = true

spacing = 4

format-mounted = <label-mounted>
format-mounted-prefix = "󱧺"
format-mounted-prefix-font = 2
format-mounted-prefix-foreground = ${color.red}
label-mounted = %used%

format-unmounted = <label-unmounted>
format-unmounted-prefix-font = 2
format-unmounted-prefix = "󱧺"
label-unmounted = %mountpoint%: not mounted

#########################################

[module/battery]
type = internal/battery

full-at = 100
low-at = 2

battery = ${system.sys_battery}
adapter = ${system.sys_adapter}

poll-interval = 2

time-format = %H:%M

format-charging = <animation-charging><label-charging>
label-charging = %percentage%%
label-charging-padding-left = 3pt

format-discharging = <ramp-capacity><label-discharging>
label-discharging = %percentage%%
label-discharging-padding-left = 3pt

format-full = <label-full>
format-full-prefix = ""
format-full-prefix-font = 2
format-full-prefix-foreground = ${color.mb}
label-full = %percentage%%
label-fill-padding-left = 3pt

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${color.blue}
ramp-capacity-font = 4

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${color.blue}
animation-charging-font = 4
animation-charging-framerate = 700

##########################################

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = true
interval = 5

reverse-scroll = false

format-volume = <ramp-volume> <label-volume>
format-volume-foreground = ${color.blue}

label-volume = %percentage%%
label-volume-foreground = ${color.purple}

format-muted = <label-muted>
format-muted-prefix = "󰖁"
format-muted-prefix-font = 2
format-muted-foreground = ${color.blue}
label-muted = "Muted"
label-muted-foreground = ${color.red}

ramp-volume-0 = ""
ramp-volume-1 = ""
ramp-volume-2 = ""
ramp-volume-3 = ""
ramp-volume-4 = ""
ramp-volume-font = 2

click-right = pavucontrol

#########################################

[module/target]
type = custom/script
exec = /usr/bin/env bash -c "${HOME}/.config/bspwm/src/target.sh"
interval = 1
format-prefix = "󰆤 "
format-prefix-font = 2
format-prefix-foreground = ${color.purple}

#########################################

[module/title]
type = internal/xwindow

format = <label>
format-prefix = ""

label = %title%
label-foreground = ${color.purple}
label-maxlen = 35

label-empty = "Machinepwn"

#########################################

[module/vpn]
type = custom/script
exec = /usr/bin/env bash -c "${HOME}/.config/bspwm/src/VPN.sh"
interval = 1
format-prefix = " 󰲚 "
format-prefix-font = 3
format-prefix-foreground = ${color.red}

#########################################

[module/brightnessctl]
type = custom/script
exec = brightnessctl -m | awk -F',' '{print $4}'
interval = 1

scroll-up = brightnessctl set +5%
scroll-down = brightnessctl set 5%-
click-left = brightnessctl set +50%
click-right = brightnessctl set 50%-

format = <label>
label = 󰖚 %output%
label-padding-left = 3pt

#########################################
