# ░█▀█░█░█░▀█▀░█▀█░█▀▀░▀█▀░█▀█░█▀▄░▀█▀
# ░█▀█░█░█░░█░░█░█░▀▀█░░█░░█▀█░█▀▄░░█░
# ░▀░▀░▀▀▀░░▀░░▀▀▀░▀▀▀░░▀░░▀░▀░▀░▀░░▀░

# Usergh0st: https://github.com/Usergh0st/dotfiles
# Date: 12.08.2026 8:08 AM
# Copyright (C) 2025-2026 ts0hg <tsohg.uncork054@passinbox.com>
# File responsible for start apps and services with hyprland.
# Enable, disable, adjust everything you want to run after hyprland.

# -- Escalate privileges --
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# -- Wallpaper administrators --
exec-once = awww-daemon &
# exec-once = hyprpaper &

# -- Waybar --
# exce-one = ~/.config/hypr/waybar/

# -- Auto-mount removable media
exec-once = udiskie &

# -- Plugins
exec-once = hyprpm reload
