# ================================================================= #          
# ▄▄ ▄▄ ▄▄ ▄▄ ▄▄▄▄  ▄▄▄▄  ▄▄     ▄▄▄  ▄▄  ▄▄ ▄▄▄▄                   #
# ██▄██ ▀███▀ ██▄█▀ ██▄█▄ ██    ██▀██ ███▄██ ██▀██                  #
# ██ ██   █   ██    ██ ██ ██▄▄▄ ██▀██ ██ ▀██ ████▀                  #
#                                                                   #
# Usergh0st - https://github.com/Usergh0st/dotfiles                 #
# Description - Central file of hyprland the orchestrator.          #
# Date - 06.08.2026 9:34 A.M                                        #
# Copyright (C) 2025-2026 Usergh0st <tsohg.uncork054@passinbox.com> #
# ================================================================= #
 
# ▄▄   ▄▄  ▄▄▄  ▄▄  ▄▄ ▄▄ ▄▄▄▄▄▄ ▄▄▄  ▄▄▄▄   ▄▄▄▄ 
# ██▀▄▀██ ██▀██ ███▄██ ██   ██  ██▀██ ██▄█▄ ███▄▄ 
# ██   ██ ▀███▀ ██ ▀██ ██   ██  ▀███▀ ██ ██ ▄▄██▀

# File responsible for configuring and. 
# Adjusting the monitors check below.
# Wiki: https://wiki.hypr.land/Configuring/Basics/Monitors/
source = ~/.config/hypr/monitors.conf

# ▄▄   ▄▄  ▄▄▄  ▄▄▄▄  ▄▄ ▄▄  ▄▄▄▄ ▄▄▄▄   ▄▄▄   ▄▄▄▄ ▄▄▄▄▄  ▄▄▄▄ 
# ██ ▄ ██ ██▀██ ██▄█▄ ██▄█▀ ███▄▄ ██▄█▀ ██▀██ ██▀▀▀ ██▄▄  ███▄▄ 
#  ▀█▀█▀  ▀███▀ ██ ██ ██ ██ ▄▄██▀ ██    ██▀██ ▀████ ██▄▄▄ ▄▄██▀ 
                                                              
# File responsible for manage virtual workspaces on Hyprland.
# Check and adjust, if you want to.
# Wiki: https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/ 

# ▄▄▄▄  ▄▄▄▄   ▄▄▄   ▄▄▄▄ ▄▄▄▄   ▄▄▄  ▄▄   ▄▄  ▄▄▄▄ 
# ██▄█▀ ██▄█▄ ██▀██ ██ ▄▄ ██▄█▄ ██▀██ ██▀▄▀██ ███▄▄ 
# ██    ██ ██ ▀███▀ ▀███▀ ██ ██ ██▀██ ██   ██ ▄▄██▀ 

# File responsible for managin the programs you commonly.
# Use, an example terminal kitty or alacritty.
source = ~/.config/hypr/programs.conf

# ▄▄ ▄▄ ▄▄▄▄▄ ▄▄ ▄▄ ▄▄▄▄  ▄▄ ▄▄  ▄▄ ▄▄▄▄   ▄▄▄▄ 
# ██▄█▀ ██▄▄  ▀███▀ ██▄██ ██ ███▄██ ██▀██ ███▄▄ 
# ██ ██ ██▄▄▄   █   ██▄█▀ ██ ██ ▀██ ████▀ ▄▄██▀ 

# File that handles all keyboard shortcuts.
# Modify or change something you don't like.
# Wiki: https://wiki.hypr.land/Configuring/Basics/Binds/
source = ~/.config/hypr/keybinds.conf

# ▄▄ ▄▄  ▄▄▄  ▄▄▄▄  ▄▄  ▄▄▄  ▄▄▄▄  ▄▄    ▄▄▄▄▄  ▄▄▄▄ 
# ██▄██ ██▀██ ██▄█▄ ██ ██▀██ ██▄██ ██    ██▄▄  ███▄▄ 
#  ▀█▀  ██▀██ ██ ██ ██ ██▀██ ██▄█▀ ██▄▄▄ ██▄▄▄ ▄▄██▀

# File responsible for managing Hyprland variables.
# Wiki: https://wiki.hypr.land/Configuring/Basics/Variables/
# source = ~/.config/hypr/variables.conf

#  ▄▄▄  ▄▄ ▄▄ ▄▄▄▄▄▄ ▄▄▄   ▄▄▄▄ ▄▄▄▄▄▄ ▄▄▄  ▄▄▄▄  ▄▄▄▄▄▄ 
# ██▀██ ██ ██   ██  ██▀██ ███▄▄   ██  ██▀██ ██▄█▄   ██   
# ██▀██ ▀███▀   ██  ▀███▀ ▄▄██▀   ██  ██▀██ ██ ██   ██  

# File responsible for initiating services and programs
# Modify or change something you don't like.
# Wiki: https://wiki.hypr.land/Configuring/Basics/Autostart/
source = ~/.config/hypr/autostart.conf

# ▄▄▄▄▄ ▄▄  ▄▄ ▄▄ ▄▄ 
# ██▄▄  ███▄██ ██▄██ 
# ██▄▄▄ ██ ▀██  ▀█▀  
                   
# File responsible for handling environment variables.
# Wiki: https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/
# source = ~/.config/hypr/env.conf

