# ░█░█░█▀▀░█░█░█▀▄░▀█▀░█▀█░█▀▄░█▀▀
# ░█▀▄░█▀▀░░█░░█▀▄░░█░░█░█░█░█░▀▀█
# ░▀░▀░▀▀▀░░▀░░▀▀░░▀▀▀░▀░▀░▀▀░░▀▀▀

# File responsible for handling Hyprland keyboard shortcuts.
# If you want to learn more, you can visit the wiki.
# Examples of keyboard shortcuts below. 

# -- Hyprland --
bind = SUPER, W, killactive
bind = SUPER, Q, exit

# -- Workspaces --
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8

bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

bind = SUPER ALT, N, movetoworkspace, -1
bind = SUPER ALT, M, movetoworkspace, +1

# -- Run Programs --
bind = SUPER, D, exec, $launcher
bind = SUPER SHIFT, F, exec, $browser
bind = SUPER, RETURN, exec, $terminal
bind = SUPER SHIFT, D, exec, $notes
bind = SUPER SHIFT, A, exec, $audiocontrol

# -- Windows -
bind = SUPER, S, togglefloating
bind = SUPER, F, fullscreen, 0
