# ░█▄█░█▀█░█▀█░▀█▀░▀█▀░█▀█░█▀▄░█▀▀
# ░█░█░█░█░█░█░░█░░░█░░█░█░█▀▄░▀▀█
# ░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░▀▀▀░▀░▀░▀▀▀

# Monitor settings: adjust resolution, refresh rate, and more.
# For more information or how to do it, you can visit the Hyprland wiki.
# Examples of configurations below

#monitor = preferred, auto, auto
monitor = eDP-1, 1920x1080@60, auto, auto
monitor = HDMI-A-2, 1920x1080@60, auto, auto
