# ░█▀█░█▀▄░█▀█░█▀▀░█▀▄░█▀█░█▄█░█▀▀
# ░█▀▀░█▀▄░█░█░█░█░█▀▄░█▀█░█░█░▀▀█
# ░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀░▀░▀░▀░▀▀▀

# Program settings variables: add the programs you use most often.
# Examples of configurations below, modify if you want.

$terminal = alacritty
$editor = nvim
$browser = firefox
$file_manager = thunar
$launcher = wofi
$lockscreen = hyprlock
