# ░█▀█░█▀▄░█▀█░█▀▀░█▀▄░█▀█░█▄█░█▀▀
# ░█▀▀░█▀▄░█░█░█░█░█▀▄░█▀█░█░█░▀▀█
# ░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀░▀░▀░▀░▀▀▀

# Program settings variables: add the programs you use most often.
# Examples of configurations below, modify if you want.

# 1
$terminal = alacritty

# 2
$editor = nvim

# 3
$browser = firefox

# 4
$file_manager = thunar

# 5
$launcher = wofi

# 6
$lockscreen = hyprlock

# 7
$notes = obsidian

# 8
$audiocontrol = pavucontrol
