# ==================================================== #
#  _______ __                   __ __   __             #
# |   _   |  |.---.-.----.----.|__|  |_|  |_.--.--.    #
# |       |  ||  _  |  __|   _||  |   _|   _|  |  |    #
# |___|___|__||___._|____|__|  |__|____|____|___  |    #
#                                           |_____|    #
#                    ___ __                            #
# .----.-----.-----.'  _|__|.-----.                    #
# |  __|  _  |     |   _|  ||  _  |                    #
# |____|_____|__|__|__| |__||___  |                    #
#                           |_____|                    #
#                                                      #
# Usergh0st - https://github.com/Usergh0st/dotfiles    #
# Description - alacritty configuration of my dotfiles #
# Date = 12.07.2026 09:46 AM                           #
# ==================================================== #

# Alacritty window how show configuration.
# config =  [ https://alacritty.org/config-alacritty.html#window ]

[window]
decorations = "Full"
opacity = 0.9
dynamic_padding = true
dynamic_title = true
padding = { x = 10, y = 10 }
startup_mode = "Windowed"
title = "Alacritty"
resize_increments = true

# Cursor configuration
# config = [ https://alacritty.org/config-alacritty.html#cursor ]

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[mouse]
hide_when_typing = true

# Selection configuration
# config = [ https://alacritty.org/config-alacritty.html#selection ]

[selection]
save_to_clipboard = true

# Scrolling config buffer
# config = [ https://alacritty.org/config-alacritty.html#scrolling ]

[scrolling]
history = 1000
multiplier = 3

# The bell configuration
# config = [ https://alacritty.org/config-alacritty.html#bell ]

[bell]
animation = "EaseOutSine"
duration = 110
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }

# The terminal shell
# config = [ https://alacritty.org/config-alacritty.html#terminal ]

[terminal.shell]
program = "/bin/zsh"
args = []

# The general config alacritty.
# config = [ https://alacritty.org/config-alacritty.html#general ]

[general]
ipc_socket = true
live_config_reload = true
working_directory = "${HOME}"
import = [
"~/.config/alacritty/colors.toml",
"~/.config/alacritty/fonts.toml",
]

# The env configuration.
# config = [ https://alacritty.org/config-alacritty.html#env ]

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

