# ========================================================= #
#  ▄▄▄  ▄▄     ▄▄▄   ▄▄▄▄ ▄▄▄▄  ▄▄ ▄▄▄▄▄▄ ▄▄▄▄▄▄ ▄▄ ▄▄      #
# ██▀██ ██    ██▀██ ██▀▀▀ ██▄█▄ ██   ██     ██   ▀███▀      #
# ██▀██ ██▄▄▄ ██▀██ ▀████ ██ ██ ██   ██     ██     █        #
#                       __                                  # 
#          .----.-----.|  |.-----.----.-----.               #
#          |  __|  _  ||  ||  _  |   _|__ --|               #
#          |____|_____||__||_____|__| |_____|               #
#                                                           #
#     ░█░█░█░█░█▀█░█▀▄░░░░░░░░░█▀▄░█▀▀░█▀█░█░█░█▄█          #
#     ░█▀█░░█░░█▀▀░█▀▄░░░▄█▄░░░█▀▄░▀▀█░█▀▀░█▄█░█░█          #
#     ░▀░▀░░▀░░▀░░░▀░▀░░░░▀░░░░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀          #
#                                                           #
# Usergh0st - https://github.com/Usergh0st/dotfiles         #
# Description - alacritty config colorshemes                #
# Wiki - https://alacritty.org/config-alacritty.html#colors #
# Version - 0.17.0                                          #
# Date = 08.08.2026 6:14 PM                                 #
# ========================================================= #

[colors.primary]
foreground = "#cd9191"
background = "#0f0f0f"

[colors.cursor]
text = "#812625"
cursor = "#261314"

[colors.vi_mode_cursor]
text = "#cd9191"
cursor = "#261314"

[colors.normal]
black = "#4A201F"
red = "#4B1F20"
green = "#4F2425"
yellow = "#732526"
blue = "#474447"
magenta = "#882726"
cyan = "#cd9191"
white = "#8f6565"

[colors.bright]
black = "#4A201F"
red = "#261314"
green = "#4B1F20"
yellow = "#4F2425"
blue = "#732526"
magenta = "#474447"
cyan = "#882726"
white = "#cd9191"
