# ======================================================= #
#  ▄▄▄  ▄▄     ▄▄▄   ▄▄▄▄ ▄▄▄▄  ▄▄ ▄▄▄▄▄▄ ▄▄▄▄▄▄ ▄▄ ▄▄    #
# ██▀██ ██    ██▀██ ██▀▀▀ ██▄█▄ ██   ██     ██   ▀███▀    #
# ██▀██ ██▄▄▄ ██▀██ ▀████ ██ ██ ██   ██     ██     █      #
#             ___               __                        #
#           .'  _|.-----.-----.|  |_.-----.               #
#           |   _||  _  |     ||   _|__ --|               #
#           |__|  |_____|__|__||____|_____|               #
#                                                         #
#       ░█░█░█░█░█▀█░█▀▄░░░░░░░░░█▀▄░█▀▀░█▀█░█░█          #
#       ░█▀█░░█░░█▀▀░█▀▄░░░▄█▄░░░█▀▄░▀▀█░█▀▀░█▄█          #
#       ░▀░▀░░▀░░▀░░░▀░▀░░░░▀░░░░▀▀░░▀▀▀░▀░░░▀░▀          #
#                                                         #
# Usergh0st - https://github.com/Usergh0st/dotfiles.git   #
# Description - Configuration of the fonts alacritty      #
# Wiki - https://alacritty.org/config-alacritty.html#font #
# Version - 0.17.0                                        #
# Date = 08.08.2026 5:27 PM                               #
# ======================================================= #

[font]

size = 12

builtin_box_drawing = true

normal = { family = "Cascadia Code", style = "SemiBold" }
bold = { family = "Cascadia Mono", style = "SemiBold" }
italic = { family = "Bai Jamjuree", style = "SemiBold" }


